states/etcd_backup.go
states/etcd_restore.go
states/force_release.go

Fix backup kv line-by-line format can not be restored correctly
/kind bug

Fix backup & restore format problem

---

states/etcd_backup.go
states/etcd_connect.go
states/etcd_restore.go
states/force_release.go
states/kill.go
states/show_collection.go
states/show_replica.go
states/show_segment.go
states/show_session.go

Signed-off-by: Wei Liu <wei.liu@zilliz.com>

add timeout to etcd operation

---

states/show.go
states/show_segment.go

Add `show segment-loaded` command

Add show segments-loaded

---

states/show.go
states/show_segment.go

Add show checkpoint command

---

states/backup_mock_connect.go
states/instance.go
states/show_segment.go

Add `clean-empty-segment` command

Add clean-empty-segment command

---

.github/mergify.yml
.github/workflows/golangci-lint.yml
OWNERS

Signed-off-by: Jenny Li <jing.li@zilliz.com>

Update mergify rule

---

states/show_segment.go

Restrict segment meta path with trailing slash

---

models/session.go
states/querycoord_cluster.go
states/show.go
states/show_querycoord_task.go
states/show_session.go
states/util.go

Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Add cmd for show querycoord cluster info

---

states/querycoord_task.go
states/show_querycoord_task.go

Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Print querycoord task in accending order

---

states/show_segment.go

Fix print start position instead of dml position

---

states/backup_mock_connect.go
states/etcd_connect.go
states/exit.go
states/garbage_collect.go
states/instance.go
states/states.go
states/util.go

Add dry mode to select milvus instance

---

.github/workflows/golangci-lint.yml
README.md
go.mod
go.sum
states/querycoord_task.go
states/show.go
states/update_log_level.go

Adapt go 1.18

---

states/backup_mock_connect.go
states/etcd_restore.go
states/show.go
states/show_index.go

Add show segment-index command

---

states/querycoord_channels.go
states/show.go
states/show_collection_load.go
states/util.go

Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Add cmd for showing loaded collections

---

states/show_segment.go

Adapt segment binlog v2.2 format

---

states/show_segment.go

Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Sort segment by id

---

states/backup_mock_connect.go
states/etcd_connect.go
states/exit.go
states/instance.go
states/states.go
states/visit_datacoord.go
states/visit_datanode.go
states/visit_indexcoord.go
states/visit_indexnode.go
states/visit_querycoord.go
states/visit_querynode.go
states/visit_rootcoord.go

Add SetupCommands for each state and call it after exec

---

go.mod
go.sum
main.go
states/cmd.go
states/states.go

Add multi-level command suggestion

---

states/show_index.go

```
SegmentID: 436322439203913731	 State: Flushed
Index build ID: 436322441666756610, state: Finished
Index build ID: 436322441666756612, state: Finished
```
Signed-off-by: Goose <jumpthepig@gmail.com>

Enable output all segment's indexes

---

states/force_release.go
states/instance.go
states/show_collection.go

Add command for release dropped collection

---

states/force_release.go
states/show_collection_load.go

Remove segments and channels after release dropped collection

---

states/force_release.go

Fix remove delta Channel prefix

---

states/force_release.go

Fix ineffectual assignment err lint issue

---

go.mod
go.sum
main.go
states/auto_complete.go
states/auto_complete_file.go
states/backup_mock_connect.go
states/cmd.go
states/states.go

Add auto-complete for
- command flags
- local file browsing
Also separate auto complete logic from states cmd type
See also #41

Add auto-complete for flags and file path

---

states/force_release.go

fix   force release  command for delete querycoord meta 
Signed-off-by: wgcn <1026688210@qq.com>

fix force release

---

states/download_segment.go
states/instance.go
states/repair_segment.go

Add command for repair 2.1 segment-index not match meta

Add repair v2.1 segment command

---

models/session.go
states/show.go
states/show_channel_watch.go
states/show_index.go
states/show_segment.go
states/util.go

Improve show index info output
- Add `show index` command
- Ignore deleted segment when show segment-index
- Print index type for segment-index

Improve show index output

---

states/backup_mock_connect.go
states/instance.go
states/show_segment.go

Signed-off-by: bigsheeper <yihao.dai@zilliz.com>
Test:

Support remove segment by id, not only empty segment

---

states/show_segment.go

Fix checkpoint calculation not excluding dropped segment

---

main.go

Accept PAGER env to redirect long output

---

states/instance.go
states/repair_channel.go

Add repair channel command

---

states/show_checkpoint.go
states/show_segment.go

Adapt Milvus2.2 Channel checkpoint

---

proto/v2.2/datapb/data_coord.pb.go
proto/v2.2/indexpb/index_coord.pb.go
proto/v2.2/querypb/query_coord.pb.go
proto/v2.2/rootcoordpb/root_coord.pb.go
states/visit.go
states/visit_datacoord.go
states/visit_datanode.go
states/visit_indexcoord.go
states/visit_indexnode.go
states/visit_querycoord.go
states/visit_querynode.go
states/visit_rootcoord.go

Improve visit command implementation

---

states/backup_mock_connect.go

Fix load v2 backup mock instance not set

---

main.go
states/exit.go
states/states.go

Fix #62 
See also c-bata/go-prompt#228
/kind bug

Fix go-prompt caused bash hijack

---

main.go

Fix pager blocks when quit early

---

states/etcd/repair/checkpoint.go

Signed-off-by: jaime <yun.zhang@zilliz.com>

Fix repair checkpoint usage

---

states/etcd/show/segment.go

Print drop ts if segment is dropped

---

states/etcd/common/segment.go

add support to inspect log path for delta and stats log
Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

Support BirdWatcher to insepect delta and stat log path for 2.2 pb

---

states/etcd/commands.go
states/etcd/common/segment.go
states/etcd/remove/segment.go
states/etcd/repair/segment_empty.go
states/etcd/show/segment.go
states/instance.go

- Rename `remove-segment-by-id` to `remove segment`
- Remove binlog files entries as well
- Add segment backup to file before removing it

Change remove-segment-by-id to remove segment

---

states/etcd/show/segment.go

add parameter --state for show segment command
Signed-off-by: MrPresent-Han <jamesharden11122@gmail.com>

support show segment according to target state #84

---

states/etcd/remove/channel.go

Fix remove channel and add more log

---

README.md

Original has depreciated command args

Update backup command

---

states/etcd/commands.go
states/etcd/show/segment.go

Print binlog field size in statistics mode

---

states/etcd/commands.go
states/etcd/common/collection.go
states/etcd/common/collection_history.go
states/etcd/common/list.go
states/etcd/show/collection_history.go

Support print collection change history from snapshots

Add show collection-history command

---

models/replica.go
states/etcd/common/replica.go
states/etcd/show/replica.go

Adapt v2.2 querycoord replica format

Adapt v2.2 Replica information format

---

Makefile
mq/factory_wkafka.go
mq/kafka/kafka.go
mq/kafka/kafka_id.go
mq/kafka/kafka_message.go
mq/kafka/kafka_test.go

Add WKAFKA build flag for control cgo(kafka) feature

---

.github/workflows/release.yaml
.gitignore
.goreleaser-darwin.yaml
.goreleaser-linux.yaml
.goreleaser-release.yaml

CI: Add goreleaser for release

---

states/etcd/audit/audit_write.go
states/etcd_connect.go

Add rootPath check for connect etcd command

---

Dockerfile

Add Dockerfile for birdwatcher

---

states/etcd/commands.go
states/etcd/remove/binlog.go

Add remove binlog file cmd

---

states/etcd/audit/audit_write.go

Fix audit log write panic

---

states/etcd/show/segment_index.go

Print segment index serialized size for debug index files

Print segment-index serialized size

---

states/etcd/common/collection_loaded.go
states/etcd/show/collection.go
states/etcd/show/collection_loaded.go

Print show collection, collection-loaded result number

---

states/etcd_connect.go

Bypass etcd rootPath check when entering dry mode
Add force flag for `connect` & `use` command
Fix #111

Fix dry mode rootPath check and add force flag

---

main.go

List suggestion items in order to make cursor stable

Make suggestion result stable

---

states/etcd/show/collection.go

Add show collection by name

---

states/etcd/show/collection.go

Fix show collection format bug

---

states/probe.go

Fix bug for metric_type is in TypeParams when probing

---

.gitignore
history/history.go
main.go
states/backup_mock_connect.go
states/etcd_connect.go
states/exit.go
states/instance.go
states/load_backup.go
states/open.go
states/start.go

Add command file history and reverse list feature(Ctrl+R)

---

bapps/olc.go
main.go
states/configuration.go
states/distribution.go
states/etcd/common/pair.go
states/instance.go

Add `one-line-command` bapp mode
Add `show configurations` command in etcd instance state
See also #118 

Add one-line-command feature and show configurations command

---

states/distribution.go

`show segment-loaded-grpc --collection [collection-id]`

Support show segment distribution by collection

---

states/force_release.go

Make force-release work with qcv2 meta

---

models/collection.go
states/etcd/commands.go
states/etcd/remove/collection_dropping.go

Add `remove collection-drop` command to clean dropping/dropped collection/channel meta

Add command to remove dropping/dropped collection meta

---

states/etcd/commands.go
states/etcd/remove/segment_collection_dropped.go

Drop segments that collection has been dropped

---

states/etcd/common/collection.go
states/etcd/show/segment_index.go

Adapt database prefix for colleciont info

---

states/etcd/common/collection.go

Iterate database prefix when invoking `common.GetCollectionByIDVersion`
See also #146 

Adapt database in GetCollectionByID logic

---

states/etcd_backup.go
states/etcd_restore.go

Batch read etcd meta when doing backup operation
Also added an option to setup batch size in case of big KV

Accelerate backup command by batch read etcd meta

---

models/partition.go
states/etcd/commands.go
states/etcd/common/partition.go
states/etcd/show/partition.go

Add show partition command

---

states/download_pk.go
states/etcd/common/channel.go
states/etcd/common/collection.go
states/etcd/repair/channel.go
states/etcd/repair/checkpoint.go
states/etcd/repair/segment.go
states/etcd/show/checkpoint.go
states/force_release.go
states/inspect_primary_key.go

Change all `GetCollectionByID` to up to date version `GetCollectionByIDVersion`
Also fixing show checkpoint fails for collection under database prefix
See also #146

Fix all GetCollectionByID usage

---

bapps/go_prompt.go
bapps/go_prompt_parser.go

Reset Raw mode before start command running

---

bapps/go_prompt_parser.go
states/etcd/show/collection.go

Add Collection create time in show collection result

---

models/collection.go
states/etcd/show/collection.go

Add dbid param for show collection cmd

---

states/backup_mock_connect.go
states/configuration.go
states/current_version.go
states/download_segment.go
states/etcd_connect.go
states/exit.go
states/instance.go
states/load_backup.go
states/open.go
states/parse_file.go
states/pulsarctl_connect.go
states/start.go
states/states.go
states/util.go
states/visit_datacoord.go
states/visit_datanode.go
states/visit_indexcoord.go
states/visit_indexnode.go
states/visit_querycoord.go
states/visit_querynode.go
states/visit_rootcoord.go

Add ability to parse command from State.XXXCommand methods
Refactor start(disconnected), etcd state command registration

Refactor command registration logic

---

states/disconnected.go

Fix missing disconnect file

---

states/probe.go

Support probing diskann

---

states/etcd/show/collection.go

Add Collection State filter option

---

models/alias.go
states/etcd/common/alias.go
states/etcd/show/alias.go
states/etcd/show/partition.go

Add show alias command

---

states/etcd/commands.go
states/etcd/repair/index_metric.go

Repair metric_type is in TypeParams instead of IndexParams

---

states/balance_explain.go
states/constants.go
states/distribution.go
states/instance.go
states/util.go

add command to release the difficulty of assessing the level of balance of milvus cluster

supporting balance explian function

---

states/etcd/commands.go
states/etcd/show/alias.go
states/etcd/show/segment_loaded.go

Add 'not supported' warning for legacy show segment-loaded command

---

common/version.go

Bump version to v1.0.2

---

go.mod
go.sum

Upgrade keyring to fix Mac warning

---

bapps/go_prompt.go
bapps/olc.go
configs/config.go
states/app_state.go

Fix olc command panicking
/kind bug

Firx one-line-command broken after AppplicationState refactoring

---

states/instance.go

Fix audit log file permission and use date suffix in name

---

models/fs_stat.go
states/app_state.go
states/segment_anaylsis.go
states/storage/minio.go
states/storage/ops.go

Add storage-analysis command

---

states/etcd/show/index.go

Add FieldID in show index output

---

states/pprof.go

Add command for auto fetch goroutine pprof

---

states/pprof.go

[CP 1.0.x] Add command for auto fetch goroutine pprof (#186)

---

.github/mergify.yml

Fix mergify DCO rule for all branches

---

states/instance.go

Cherry-pick from main #181 
/kind bug

[CP 1.0.x] Fix audit log file permission and use date suffix in name (#181)

---

common/version.go
states/etcd/show/collection_loaded.go
states/etcd/show/index.go

Cherry pick commands improvement from #184 #190

Cherry-pick command improvement and bump version to v1.0.3

---

.github/mergify.yml

Fix dco-pass rule in mergify check for v1.0.x branch

---

states/etcd_connect.go

Suppport connect to ETCD with tls cerificate

---

states/etcd/show/partition.go
states/etcd/show/segment.go

Fix partition filter not working for `show segment`

---

.github/mergify.yml

Fix mergify rules not using regex

---

states/etcd/remove/binlog.go

pr: https://github.com/milvus-io/birdwatcher/pull/202

Support remove one binlog from field binlogs (#202)

---

states/etcd/common/collection_history.go
states/etcd/show/collection_history.go

Fix collection history not found for collection with database prefix

---

models/user.go
states/etcd/common/list.go
states/etcd/common/user.go
states/etcd/show/user.go

Add `show user` command

---

states/etcd/show/segment.go

Show the number of dropped segments

---

states/etcd/show/alias.go

Add create timestamp output for show alias

---

proto/v2.2/datapb/data_coord.pb.go
proto/v2.2/gen_proto.sh
proto/v2.2/indexpb/index_coord.pb.go
proto/v2.2/milvuspb/milvus.pb.go
proto/v2.2/querypb/query_coord.pb.go
proto/v2.2/rootcoordpb/root_coord.pb.go

fix script does not rectify service package name and missing new proto replacement

Fix gen proto script for proto/v2.2 pkg

---

states/etcd/show/segment.go

add FieldBinlog size & Segment Binlog size summary output for detailed table view

Add segment,field level binlog size summary

---

states/etcd/show/segment.go

Print statslog and deltalog size summary in segment level

enhance: Print segment stats/deltalog size aggregration

---

common/version.go
mq/msg.go

Bump birdwatcher version for release

enhance: Bump v1.0.4

---

states/etcd/commands.go
states/etcd/repair/manual_compaction.go

enhance: manual compaction trigger

---

states/etcd/show/segment.go

support filter segment with segment level with `--level` option
also make state & level case insensitive

enhance: Support filter segment with segment level

---

states/etcd/commands.go
states/etcd/repair/collection_legacy.go
states/etcd/repair/component.go
states/instance.go

See also milvus-io/milvus#33608
Command removes collection with no field to fix the bug in previously mentioned issue

enhance: Add `repair legacy-collection-remnant` command

---

states/etcd/common/collection_history.go
states/etcd/repair/collection_legacy.go
states/etcd/show/collection_history.go

fix: Remove collection history item when repairing legacy collection

---

models/database.go
models/resource_group.go
states/etcd/common/replica.go
states/etcd/common/resource_group.go
states/etcd/show/resource_group.go

ResourceGroup is important for multi-tenants maintanence. This PR adds `show resource-group` command to list this entities.

enhance: Support `show resource-group` command

---

states/etcd/show/segment_index.go

enhance: Support filter `show segment-index` result with field ID

---

models/collection.go
models/collection_schema.go
states/etcd/show/collection.go

Support printing array field element data type for `show collections` command

enhance: Print Array field element type

---

go.mod
go.sum
oss/aliyun.go
oss/minio.go
oss/tencent.go
states/minio.go

Aliyun OSS was banned for minio adaptation issue. This PR add it back after verification.

enhance: Support aliyun as oss source

---

oss/minio.go
oss/tencent.go
states/scan_binlog.go

Add tencent myqcloud support with `tke` & `cvm` credential

enhance: Support Tencent myqcloud as OSS source

---

states/etcd/commands.go
states/etcd/remove/compaction_task.go

all remove command shall have `run` flag

enhance: Add `Run` flag for remove compaction command

---

.github/workflows/golangci-lint.yml
states/etcd/repair/channel_watched.go

Use cockroachdb error lib, trying to fix lint issue

fix: Upgrade golangci-lint workflow go version to v1.21

---

bapps/go_prompt.go
bapps/go_prompt_parser.go

Cherry-pick from master
pr: #315
Related to #314

fix: [Cherry-pick] Remove unused Unsafe reflection code (#315)

---

states/etcd/common/collection.go
states/etcd/restore/collection.go
states/etcd/set/collection_consistency_level.go
states/etcd/set/component.go
states/instance.go

Add command to update collection default consistency level

enhance: Support `set collection consistency-level` command

---

states/etcd/remove/compaction_task.go

Add task state & collection, partition id filter for remove compaction command.

enhance: Add filter for `remove compaction` command

---

states/distribution.go

Add node filter for `show segment-loaded-grpc` command to make it easier finding segment distribution when querynodes number is large.

enhance: Add node filter when show segment loaded via grpc

---

states/etcd/show/segment.go

Add total delta entry number for `show segment --format statistics` output result

enhance: Add delta entry number statistics for segment output

---

states/etcd_connect.go

This PR set etcd address to default 2379 port if user param does not contain port.

enhance: Use default etcd port 2379 when port not passed

---

.goreleaser-darwin.yaml
.goreleaser-linux.yaml

goreleaser failed to build due to main.go move to cmd pkg after pr #332

enhance: Update goreleaser build main config

---

states/etcd/repair/field_index.go
states/etcd/repair/index_duplicate.go

Add command to scan duplicate index and repair issue

enhance: Add `repair index-dup` command

---

models/session.go
states/etcd/show/session.go

Refine show session command output by
- Add main/stand-by indicator
- Group session by component type

enhance: Refine `show session` output

---

models/session.go
states/etcd/show/session.go

Refine show session command output by
- Add main/stand-by indicator
- Group session by component type
---------

enhance: Refine `show session` output (#366)

---

states/visit.go
states/visit_datacoord.go

Add flush cmd for visit datacoord state
Also add compactAll flag in case of miss op

enhance: Add flush cmd and refine compact cmd

---

states/etcd/show/collection.go

Add field schema nullable & default value attribute for `show collection` command output

enhance: Support display nullable and default value

---

states/etcd/show/index.go
states/etcd/show/segment_index.go
states/mgrpc/datacoord.go

This PR:
- Print underlining index param & user params kvs
- Add indexID filter and print it for show segment-index command

enhance: Print index user params and refine segment index output

---

states/probe.go
states/util.go

This PR:
- Use `QuerySegments` interface instead of legacy `Query`
- Rewrite `probe pk` command with bw framework
- Add output fields parameter

enhance: Refine probe pk command

---

states/etcd/show/compaction.go

`cleaned` & `completed` tasks could be too noisy for large collection. This PR add `ingoreDone` flag fow `show compactions` command and set default value to true

enhance: Add ignoreDone flag for show compactions command

---

storage/binlog/v2/binlog_reader.go
storage/segment_reader.go

Use correct offset when storage v2 using multiple reader

Fix: multi RecordReader offset issue

---

states/etcd/common/collection.go
states/healthz.go
states/healthz/check_item.go
states/healthz/issue_43407.go
states/healthz/queryview_lag.go
states/mgrpc/connect.go

This patch add abstraction for healthz check item and update healthz-check command logic.
Also:
- Add ISS43407 check item
- Add list healthz item
- Refine mgrpc connect logic

enhance: Add healthz check items and related commands

---

states/etcd/common/wal_recovery_storage.go
states/wal_message_id.go

enhance: add message id guess tool

---

states/healthz/check_item.go
states/healthz/loaded_index_missing.go

Add healthz check time for loaded segment missing built indexes

enhance: Add healthz check item for missing index

---

states/etcd/show/session.go

Make `show session` command output support json format to make user easier to integrate bw using binary execution output.

enhance: Support print session as json
