states/states.go
states/visit.go
states/visit_datacoord.go
states/visit_datanode.go
states/visit_indexcoord.go
states/visit_indexnode.go
states/visit_querycoord.go
states/visit_rootcoord.go

Clear the nextState as app go to next state to prevent some bugs that occur after the app back to last state.
Add datacoord, datanode, indexcoord, indexnode, querycoord,rootcoord to the visit cmd as an alternative session types.
Add Cmd GetMetrics for all alternative session types.

Add GetMetrics

---

states/download_pk.go
states/download_segment.go
states/garbage_collect.go
states/inspect_primary_key.go
states/repair_segment.go
states/show_segment.go

Fill Milvus2.2 segment binlog lazy

---

models/backup_header.go
states/backup_mock_connect.go
states/etcd_backup.go
states/etcd_restore.go
states/force_release.go
states/instance.go
states/metrics.go

Implement backup v2 to fetch extra meta for milvus

---

.dockerignore
states/backup_mock_connect.go
states/etcd/commands.go
states/etcd/common/channel.go
states/etcd/common/collection.go
states/etcd/common/list.go
states/etcd/remove/channel.go

Add `remove channel` command to remove orphan watch channel info from datacoord meta.

Add remove orphan watch channel command

---

states/probe.go

Fix probe query failed due to search param need to be number in 2.2.x
/kind bug

Fix hnsw probe search request ef param type

---

states/autocomplete/auto_complete.go
states/autocomplete/auto_complete_file.go
states/load_backup.go
states/parse_file.go
states/start.go
storage/event_reader.go
storage/index_reader.go
storage/payload_reader.go

Add commands
- parse-indexparams
- assemble-indexfiles
- validate-indexfiles
Related to #116 

Add indexfile process commands

---

states/etcd/commands.go
states/etcd/remove/channel.go

Add short description for  cmd in backup mode

---

bapps/app.go
bapps/go_prompt.go
bapps/promptui.go
history/history.go
main.go

Add `bapps.BApp` interface (BApp short for Birdwatcher application)
Wraps `go-prompt` and `promptui` as BApp
Move app logic to bapps package to make code cleaner

Add BApp abstraction for go-prompt and promptui

---

states/probe.go

Add `probe pk` command
See also #105 

Add probe pk command

---

states/etcd/commands.go
states/etcd/common/config_etcd.go
states/etcd/set/etcd_config.go
states/etcd/show/config_etcd.go
states/instance.go

Add show/set etcd-confg commands

---

.gitignore
states/etcd/common/collection.go
states/etcd/common/segment.go
states/instance.go
states/verify_segment.go

This PR contains following changes:
- Add `verify-segment` command to check storage files matches meta
- Fix statslog path in segment information
- Fix GetCollectionByID key usage value bug
See also #145

Add verify-segment command

---

bapps/webserver.go
framework/resultset.go
main.go
models/channel_watch.go
models/data_type.go
models/segment.go
states/configuration.go
states/current_version.go
states/etcd/show/alias.go
states/etcd/show/channel_watched.go
states/etcd/show/checkpoint.go
states/etcd/show/collection.go
states/etcd/show/collection_history.go
states/etcd/show/collection_loaded.go
states/etcd/show/database.go
states/etcd/show/partition.go
states/etcd/show/replica.go
states/etcd/show/session.go
states/exit.go
states/instance.go
states/states.go

Related to #154
- Add rest server app mode
- Add web server auto parsing handler framework
- Adapt basic meta information `show` command for `GET` methods

Add web server & auto handler parser for show commands

---

framework/state.go
states/app_state.go
states/balance_explain.go
states/configuration.go
states/current_version.go
states/distribution.go
states/etcd_backup.go
states/instance.go
states/management.go
states/probe.go

Change list:
- Fix sub state transfer might not work for multiple sub state attached
- Change `dry-mode`, `backup` and `current-version` commands to framework format
- Remove all deprecated `WithInsecure` grpc dial option
- Add `debug commands` utility command for debug current command tree

Fix ApplicationState sub state transfer

---

framework/state.go

Use the root ancestor of `CmdState` to spawn in case of multiple generation caused missing commands

Fix multi generation cmd logic error

---

README.md

fail to install by `go install xxx`
reason:  
> If there are replace or exclude directives in the module, the correct installation method is to clone the source and install it, there's no reason to recommend otherwise.
detail: https://stackoverflow.com/questions/69807151/go-install-github-com-dmacvicar-terraform-provider-libvirtlatest-shows-error

Update the installation comment

---

.gitignore
states/app_state.go
states/backup_mock_connect.go
states/etcd/show/collection_loaded.go
states/etcd/show/index.go

Fix embedEtcdState command missing

---

states/etcd/show/collection.go

when getting collections info based on state, the judgement for collection state is not correct

fix wrong operation for getCollectionBy State

---

.gitignore
states/distribution.go
states/etcd/show/segment.go

- Add small segment number & row count summary
- Add total sealed segment count for segment loaded distribution

[1.0.x] enhance: improve show segment & distribution result output

---

states/kv/kv.go
states/kv/utils.go

Since `path.Join` will remove tailing slash, the newly added kv implementation will return some other kv values when prefix need this tailing slash.
Add a util function to keep this tailing slash and replace all `path.Join` in kv impl with it
Fix #213

Keep tailing slash for kv operations

---

states/etcd/show/segment.go

support storage analysis with statistics (#215)

---

states/etcd/commands.go
states/etcd/common/collection.go
states/etcd/common/segment.go
states/etcd/remove/collection_clean.go
states/kv/kv.go
states/kv/kv_audit.go

Add remove leaked collection meta cmd

---

states/etcd/commands.go
states/etcd/common/collection.go
states/etcd/common/segment.go
states/etcd/remove/collection_clean.go

[CP 1.0.x] Add remove leaked collection meta cmd

---

states/etcd_restore.go
states/load_backup.go

Previously the `load-backup` command cost lots of time if there are numerous kv pairs in backup file.
This PR accelerate this procedure with
- Batching the KV entries before writing into embed etcd
- Use multiple workers to execute the put transaction
For 110k kv backup file, this could improve load time from about 5.5 minutes to around 15 seconds.
are numerous

enhance: accelerate `load-backup` command speed

---

states/configuration.go
states/etcd/show/index.go

enhance: add config key filter for `show configurations` cmd

---

framework/resultset.go
states/healthz.go

Add healthz-check command to check segment target block problem

enhance: Add healthz-check command

---

states/distribution.go

Growing segment could be in `GrowingSegments` or `GrowingSegmentIDs` field in LeaderView
This handles either case when get segment distribution

fix: Get growing segment id when growing info is in GrowingSegments

---

go.mod
states/binlog.go
states/check_partition_key.go
states/download_segment.go
states/etcd/common/segment.go
states/hash.go
states/inspect_primary_key.go
states/minio.go
storage/binlog_reader.go
storage/binlog_reader_test.go
storage/delta_data.go
storage/deltalog_reader.go
storage/index_reader.go
storage/parquet_reader.go
storage/parquet_writer.go
storage/payload_reader.go
storage/primary_key.go
storage/primary_keys.go

See also milvus-io/milvus#30607
This command could scan binlogs for milvus instance and check partition key data is located in wrong partition due to previously mentioned issue

enhance: Add check-partition-key command to export partition key error data

---

states/etcd/remove/collection_dropping.go

When collection with provided id not exist, birdwatcher will have NPE panic
Also add log and return fast when list collection fails in same command

fix: Fix panicking in `remove collection-drop` when collection not exist

---

states/check_partition_key.go
states/frame_screen.go

enhance: Improve the prompt information when checking partition-key errors

---

mq/factory.go
mq/factory_wkafka.go
mq/ifc/msgstream.go
mq/ifc/options.go
mq/pulsar/pulsar_test.go
mq/pulsar/puslar.go
states/consume.go
states/etcd/repair/checkpoint.go

Add `consume` command. It subscribe top provided topic and consume until the latestID. If `detail` flag is false, this command prints only the message type. Otherwise, the Insert/Delete msg body will be printed.

enhance: Add `consume` cmd to read data from provided topic

---

go.mod
states/etcd_connect.go

Use with block dial option when create etcd client so that dry connect may detect bad etcd address as well.

fix: [1.0.x] Add WithBlock option when connecting Etcd

---

states/etcd/remove/channel.go

- List collection with lastest logic
- If all collections are gone, make `remove channel` workable

fix: Make `remove channel` works when collection meta gone

---

models/collection_loaded.go
models/partition_loaded.go
states/backup_mock_connect.go
states/etcd/audit/audit.go
states/etcd/common/collection.go
states/etcd/common/collection_loaded.go
states/etcd/common/partition_loaded.go
states/etcd/show/checkpoint.go
states/etcd/show/collection.go
states/etcd/show/collection_loaded.go
states/etcd/show/index.go
states/etcd/show/partition_loaded.go
states/force_release.go
states/instance.go

See also #255
This PR:
- Add `show partition-loaded` command to list partitions loaded
- Make `force-release` able to specify collection id
- Rewrite `force-release` command with new framework
- Some minor format/parameter usage fix

enhance: Add `partition-loaded` and make `force-release` selectable

---

states/etcd/remove/channel.go

In some cases, dev-ops might remove channel ignoring collection status. This pr add `force` flag to remove channel whatever collection status might be.

enhance: Add `force` flag for `remove channel` command

---

.golangci.yml
mq/factory.go
mq/factory_wkafka.go
mq/ifc/msgstream.go
mq/kafka/kafka.go
mq/kafka/kafka_id.go
mq/kafka/kafka_test.go
mq/pulsar/pulsar_id.go
mq/pulsar/puslar.go
states/consume.go

See also #252
Add Kafka support for `consume` command.
Make it possible to consume from channel checkpoint if any

enhance: Support `consume` command with Kafka MQ

---

bapps/go_prompt.go

For history suggestion mode, suggestion item will be appended after last space, which may cause incorrect input for multi-word commands, say:
`show collections` after suggetions became `show show collections`
This PR make suggestion item trim parts before last space.

enhance: Refine history suggestion when input contains spaces

---

configs/config.go

Birdwatcher shall put history log in workspace folder. If the folder does not exist, history logging will fail. This PR make birdwatcher to try to create folder by default and try it best to enable history logging

enhance: Add setup workspace step to enable history by default

---

configs/config.go
states/download_pk.go
states/etcd_backup.go
states/instance.go
states/pprof.go
states/visit.go

Fetching pprof may cause lots of time especially when the type is set to
`profile` since the birdwatcher will fetch each component for 30 seconds
This PR make this procedure run in parallel to improve the performance
of `pprof` command

enhance: Make pprof fetching run in parallel

---

states/etcd_connect.go

Find instance rootPath is painful, this PR add auto flag to find milvus rootPath in etcd. 
If there is only one candidate, connect command will use it automatically

enhance: Add auto detect rootPath for connect command

---

states/etcd/show/segment.go

enhance: Show mem size in statistics

---

states/download_segment.go
states/instance.go
states/minio.go

Make `download-segment` work for gcp as well

enhance: Use auto oss access detection for download-segment

---

go.mod
go.sum

Add `github.com/quasilyte/go-ruleguard/dsl` dependency for ruleguard lint

fix: Add ruleguard dependency

---

states/etcd/common/database.go
states/etcd/show/database.go

Make `show database` command accept `--name` argument
to filter database result by name.

enhance: Filter `show database` result by name

---

models/collection.go
models/collection_schema.go
states/etcd/show/collection.go

Clustering key is new for major compaction debugging. This PR add field clustering key attribute output in `show collection`.

enhance: Display collection clustering key info

---

states/backup_mock_connect.go
states/current_version.go
states/download_pk.go
states/download_segment.go
states/inspect_primary_key.go
states/instance.go
storage/binlog_reader.go
storage/index_reader.go

`inspect-pk` command is hidden after new command detection arch. This PR export it and make it better to support scan remote binlog without writing them into local files.

enhance: Refine inspect-pk command to support remote mode

---

models/session.go
states/etcd/common/session.go
states/etcd/remove/session.go

This PR add `remove session --component [service] --sessionID [id]` command to clean or force kill session.

enhance: Add `remove session` command

---

states/etcd/show/database.go

It become a valid need that user wants to find database information from collection dbid. This PR add filter ability with dbid when showing database information.

enhance: Support show database filter with dbid

---

states/etcd/show/channel_watched.go

Add `withoutSchema` & `printSchema` flag for `show channel-watch` command

enhance: Add schema flags for channel watch command

---

oss/minio.go
states/binlog.go
states/check_partition_key.go
states/download_pk.go
states/download_segment.go
states/inspect_primary_key.go
states/minio.go
states/scan_binlog.go

The bucket existence check need extra permission, this could block online check.
This PR enable to skip bucket existence check.

enhance: Add flag to control skip bucket exist check

---

states/scan_binlog.go

This PR applies deletion from deltalog(segment itself & l0 segments) when scanning binlogs.

enhance: Apply deltalog when scanning binlog

---

go.mod
states/etcd/remove/compaction_task.go

Duplicated method name from different embed struct causing command failed to work

enhance: Rename duplicated compaction task command

---

states/balance_explain.go
states/configuration.go
states/distribution.go
states/etcd/common/session.go
states/etcd/download/distribution.go
states/etcd/remove/session.go
states/etcd/repair/channel.go
states/etcd/repair/manual_compaction.go
states/etcd/show/legacy_qc_cluster.go
states/etcd/show/session.go
states/etcd_backup.go
states/healthz.go
states/instance.go
states/management.go
states/metrics.go
states/minio.go
states/pprof.go
states/probe.go
states/update_log_level.go
states/util.go
states/visit.go

This PR:
- Use framework style to re-write this command
- Add row count information in output for balance info
- Group segment by collection
- Add `ctx` parameter for all list session util func

enhance: Refine `show segment-loaded-grpc` command

---

docs/bw_framework.md

Add document for command detction framework:
- naming rules
- signature rules
- embedding struct

doc: Add markdown document for command detection framework

---

states/etcd_connect.go

Add username/password auth method for connecting etcd

enhance: Support username/password ETCD credential

---

.github/workflows/release.yaml

generic deduction does not work well in 1.18
upgrading go tool version to 1.21 releasing new code

enhance: Upgrade goreleaser go version to 1.21

---

.github/workflows/release.yaml

Cherry pick #325 
generic deduction does not work well in 1.18
upgrading go tool version to 1.21 releasing new code

enhance: [Cherry-pick] Upgrade goreleaser go version to 1.21

---

states/etcd/show/replica.go

This PR refines the output information from `show replica` command
- Output printed grouping by collection
- Add collection name information
- Add ResourceGroup information
- Sort node id in case of comparison

enhance: Refine `show replica` output

---

states/scan_binlog.go
states/scan_deltalog.go

Add `scan-deltalog` command to scan deltalogs and locate specified existence

enhance: Support `scan-deltalog` command

---

states/etcd/common/bulkinsert.go

fix: https://github.com/milvus-io/birdwatcher/pull/329

fix: Fix remove bulkinsert job command

---

states/backup_mock_connect.go
states/etcd/show/alias.go
states/etcd/show/bulkinsert.go
states/etcd/show/channel_watched.go
states/etcd/show/checkpoint.go
states/etcd/show/collection.go
states/etcd/show/collection_history.go
states/etcd/show/collection_loaded.go
states/etcd/show/compaction.go
states/etcd/show/component.go
states/etcd/show/config_etcd.go
states/etcd/show/database.go
states/etcd/show/index.go
states/etcd/show/partition.go
states/etcd/show/partition_loaded.go
states/etcd/show/replica.go
states/etcd/show/resource_group.go
states/etcd/show/segment.go
states/etcd/show/segment_index.go
states/etcd/show/segment_loaded.go
states/etcd/show/session.go
states/instance.go

The basePath & metaPath shall be separated since most of meta info are stored under metaPath but some other info (say config-etcd) are stored under basePath

fix: Separate basePath & metaPath to show config-etcd

---

states/scan_binlog.go
states/scan_deltalog.go

Previously, scan-binlog command need to manually provide outputFields for pk column even the pk column & ts column is always fetched.
This PR unifies `scan-binlog` & `scan-deltalog` command to have the default `$pk` & `$timestamp` env value for filter expression.

enhance: Add default $ps & $timestamp env for scan expr

---

states/etcd/common/index.go
states/etcd/repair/segment.go
states/etcd/show/segment_index.go

Previously common.ListSegmentIndex has default timeout of 3 seconds, which could cause command fail when segment index number is large

enhance: Pass ctx for `common.ListSegmentIndex` instead

---

.github/workflows/release.yaml

Related to https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

enhance: Upgrade artifacts upload/download action version

---

states/scan_binlog.go

Output example
```
=== start to execute "locate" task with filter expresion: "id==556505" ===
entry found, segment 456391498725960756 offset 138210, pk: 556505, ts: 456391398954631189
binlog batch 1, pk binlog ROOT_PATH/insert_log/456390691419325481/456390691419325482/456391498725960756/100/456391498725962722
```

enhance: Output ts when locate pks

---

states/scan_binlog.go

Output example
```
=== start to execute "locate" task with filter expresion: "id==556505" ===
entry found, segment 456391498725960756 offset 138210, pk: 556505, ts: 456391398954631189
binlog batch 1, pk binlog ROOT_PATH/insert_log/456390691419325481/456390691419325482/456391498725960756/100/456391498725962722
```

enhance: Output ts when locate pks (#363)

---

states/probe.go

Add `--mvccTimestamp` param for probe pk command

enhance: Support specify mvccTimestamp for `probe pk`

---

states/etcd/show/session.go

Milvus 2.6 merged coordinator sessions into one. Old session prefix may fail to list the corect session item.

enhance: Adapt 2.6 mixcoord session

---

states/minio.go

Milvus 2.6 merged coordinator sessions into one. Adapt 2.6 minio session check to include mixcoord

enhance: Adapt 2.6 minio session check to include mixcoord

---

states/etcd/show/segment.go

After storage v2 integrated, storage version is crucial when debuging milvus behavior

enhance: Print storage version of segment

---

storage/segment_reader.go

Previously, only first rg is processed which may cause missing data when scan binlog

fix: Iterate next rg when RecordReader return EOF

---

go.mod
states/scan_binlog.go
storage/segment_iterator.go

This previous used `i` is the offset in record batch not the design entry offset in file batch.
This PR make the offset represent the correct value by iterating it outside of recordBatch loop.
Also add `partitionID` filter and fix go.mod missing dep.

enhance: Rectify entry offset when scanning binlog
